{% set name = "physicsml" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/physicsml-{{ version }}.tar.gz
  sha256: 80faf6282107cc5f1066969d29261c235f7e31ff175e64d2d065a33940f1258a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=64.0.0
    - setuptools-scm >=6.2.0
    - pip
  run:
    - torch-geometric >=2.5.0
    - python >=3.8
    - molflux >=0.5.0
    - pytorch >=2.0
    - lightning >=2.1
    - pytorch_geometric >=2.5.0
    - e3nn
    - torchani !=2.2.4

test:
  imports:
    - physicsml
  commands:
    - pip check
  requires:
    - pip

about:
  summary: A package for all physics based/related models
  home: https://github.com/Exscientia/physicsml
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
